# Generated by Django 5.0.6 on 2024-06-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
